Repository AIBauchi/PyDS-A, pull requests merged in 2023-10, with the labels that each got.

#15 Quick Sort #13
  pyds_a/algorithms/sorting/quick_sort.py
  pyds_a/algorithms/sorting/quicksort.py
Labels: enhancement, hacktoberfest, sub task, hacktoberfest-accepted

#24 Adds merge sort
  pyds_a/algorithms/sorting/merge_sort.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#39 Adds bucket_sort.py
  pyds_a/algorithms/sorting/bucket_sort.py
Labels: enhancement, hacktoberfest, sub task, hacktoberfest-accepted

#53 implement insertion_sort.py
  pyds_a/algorithms/sorting/insertion_sort.py
Labels: enhancement, good first issue, hacktoberfest, learn, sub task, hacktoberfest-accepted

#50 Implement Singular Linked List
  pyds_a/data_structures/singly_linked_list.py
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest-accepted

#48 Implementing Depth First Search
  pyds_a/algorithms/searching/depth_first_search.py
Labels: enhancement, hacktoberfest, sub task, hacktoberfest-accepted

#57 Create countsort.py
  pyds_a/algorithms/sorting/countsort.py
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#58 added primality testing algos
  pyds_a/algorithms/numerical/millerRabin.py
  pyds_a/algorithms/numerical/sieveOfEratosthenes.py
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#64 Create trie.py
  pyds_a/data_structures/trie.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
